import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "src/data/citizens-charter/citizens-charter.json"

def req(name, source): return {"requirement": name, "where_to_secure": source}
def step(n, action, agency, fee, time, people): return {"step": n, "action": action, "agency_action": agency, "fees": fee, "processing_time": time, "person_responsible": people}
def common(name, classification, transaction, requirements, steps, fees, total, people):
    return {"plain_language_name": name, "classification": classification, "type_of_transaction": transaction, "requirements": requirements, "client_steps": steps, "fees": fees, "processing_time": total, "person_responsible": people}

ENGINEER = ["Building Inspector I", "Engineering Assistant", "Administrative Aide IV", "Acting City Engineer", "Office of the City Engineer"]
updates = {
"Excavation Permit Issuance": common("Excavation Permit for Water Lines and Connections", "Simple", "G2C / G2B - Government to Citizen or Business", [req("Excavation Form (2 copies)", "Office of the City Engineer"), req("Request from the Water District", "Meycauayan Water District"), req("Barangay Clearance (original and 1 photocopy)", "Barangay Hall where excavation will occur"), req("Sketch with landmarks", "Owner"), req("Community Tax Certificate (1 photocopy)", "Barangay Hall or City Treasurer")], [step(1,"Submit the completed form and requirements.","Review the documents.","None","3 minutes",ENGINEER),step(2,"Assist during the ocular inspection.","Conduct the inspection.","None","1 day, as scheduled",ENGINEER),step(3,"Wait for the Order of Payment, then pay at the City Treasurer.","Issue the Order of Payment, receive payment, and issue the receipt.","Residential: PHP 500; commercial: PHP 700","46 minutes",ENGINEER),step(4,"Present the receipt and receive the permit.","Prepare and release the Excavation Permit.","None","21 minutes",ENGINEER)], {"amount":"PHP 500-PHP 700","description":"Residential: PHP 500; commercial: PHP 700."}, "1 hour and 10 minutes, plus 1 day for inspection", ENGINEER),
"Fencing Permit Issuance": common("Fencing Permit", "Simple", "G2C / G2B - Government to Citizen or Business", [req("Notarized Fencing Permit Forms (3 copies)","Office of the City Engineer"),req("Land title and latest Tax Declaration/Real Property Tax Receipt", "Registry of Deeds, City Assessor, or owner"),req("Barangay Clearance and Community Tax Certificate", "Barangay Hall or City Treasurer"),req("Fencing Plan (5 original sets), Lot Plan (3 originals), and Bill of Materials (3 originals)","Licensed civil engineer/architect and owner"),req("DOLE Construction Safety and Health Program document", "DOLE Malolos")], [step(1,"Submit the notarized form and requirements.","Review the documents.","None","10 minutes",ENGINEER),step(2,"Assist during ocular inspection.","Conduct the inspection.","None","1 day, as scheduled",ENGINEER),step(3,"Wait for the Order of Payment, pay at the cashier, and secure the receipt.","Assess the fee, receive payment, and issue the receipt.","Based on the Fencing Permit Assessment Schedule","40 minutes",ENGINEER),step(4,"Present the receipt and receive the permit.","Prepare and release the Fencing Permit.","None","23 minutes",ENGINEER)], {"amount":"See assessment schedule","description":"Calculated by fence material, height, length, paved area, sidewalk occupancy, and scaffolding use under the Charter schedule."}, "1 hour and 13 minutes, plus 1 day for inspection", ENGINEER),
"Procedure for Hemodialysis Treatment": common("Hemodialysis Treatment", "Simple", "G2C - Government to Citizen", [req("Confirmed treatment schedule","City of Meycauayan Dialysis Center"),req("Patient kit: oxygen cannula and mask, paracetamol, clonidine, diphenhydramine, and face mask","Patient")], [step(1,"Proceed to triage and complete the health declaration.","Assess vital signs and condition and clear the patient for treatment.","None","5 minutes",["Dialysis Nurses","CMDC"]),step(2,"Proceed to the waiting area.","Record weight, vital signs, physical assessment, ultrafiltration computation, and prepare the patient.","None","25 minutes",["Dialysis Nurses","CMDC"]),step(3,"Proceed to treatment.","Perform and monitor dialysis, terminate treatment, reassess the patient, give home-care instructions, and issue the discharge slip.","None","4 hours and 24 minutes",["Dialysis Nurses","CMDC"]),step(4,"Receive the discharge slip and proceed to the Patient Business Office.","Record services provided and direct the patient to discharge processing.","None","6 minutes",["Dialysis Nurses","CMDC"])], {"amount":"None","description":"No treatment fee is listed in this procedure; subsequent billing follows the discharge process."}, "5 hours", ["Dialysis Nurses","City of Meycauayan Dialysis Center"]),
"Admitting Section": common("Ospital ng Meycauayan Patient Admission", "Simple", "G2C - Government to Citizen", [req("Patient Information Sheet and OSMEYC Patient ID Card or valid government ID","Ospital ng Meycauayan Admitting Section"),req("For admission: completed Admission and Discharge Record, consent for diagnosis/treatment, and doctor's admission order","Emergency, outpatient, or medical staff")], [step(1,"Complete and submit the Patient Information Sheet and valid ID.","Check, interview, validate, and encode the patient's information; print and issue the Patient ID Card.","None","19 minutes",["Admitting Staff","Patient or Companion"]),step(2,"For admission, obtain medical endorsement; OPD/direct admissions complete the admission information.","Verify the admission record, consent, and doctor's order; encode the admission, prepare the wrist tag, orient the patient, and direct them to medical social service.","None","26 minutes",["Admitting Staff","Medical Staff","Patient or Companion"])], {"amount":"None","description":"No fee"}, "45 minutes", ["Admitting Staff","Ospital ng Meycauayan"]),
"Truck Ban and Total Truck Ban Exemption Certificate Issuance": common("Truck Ban Exemption Certificate", "Complex", "G2C / G2B - Government to Citizen or Business", [req("Request letter describing goods/services, origin, destination, and truck plate numbers","Client"),req("Truck registration and updated official receipt with readable QR code","LTO"),req("Printed front and side photos of each truck","Client"),req("Valid Business Permit","LGU at place of business"),req("Proof of delivery/order, contract, endorsement, or other justification for travel in Meycauayan","Client or concerned establishment")], [step(1,"Submit the request and complete requirements.","Validate the submission and provide the application form.","None","1 hour",["Senior Administrative Assistant II","Office of the City Administrator"]),step(2,"Complete and submit the application.","Screen and route the application, obtain Mayor approval, seal and copy the certificate, and notify the client.","None","6 days, 1 hour, and 10 minutes",["Traffic Management Screening Committee","City Administrator","City Mayor"]),step(3,"Return, sign the logbook, and receive the certificate.","Record and release the approved exemption certificate.","None","20 minutes",["Senior Administrative Assistant II","Office of the City Administrator"])], {"amount":"None","description":"No fee listed. Truck Ban and Total Truck Ban certificates require separate applications and are valid for 6 months."}, "6 days, 2 hours, and 30 minutes", ["Office of the City Administrator","Traffic Management Screening Committee","City Mayor"]),
"Closed-Circuit Television (CCTV) Footage Issuance": common("Request for City CCTV Footage", "Simple", "G2C - Government to Citizen", [req("Completed CCTV Request Form","CCTV Room, 6th Floor, City Hall"),req("Police report, blotter, or incident report (1 photocopy)","PNP, Barangay, or concerned city office"),req("Flash drive when footage is at least 3 minutes long","Client")], [step(1,"Submit the request form and incident record to the CCTV Unit.","Verify, record, assess, route for City Administrator recommendation and Mayor approval, retrieve the footage, and notify the client. Short clips may be sent electronically.","None","2 days, 1 hour, and 30 minutes",["CCTV Operator","City Administrator","City Mayor"]),step(2,"For clips of 3 minutes or longer, return with a flash drive.","Save the footage, obtain the client's release-log signature, and release the storage device.","None","1 hour",["CCTV Operator","Office of the City Administrator - CCTV Unit"])], {"amount":"None","description":"No fee"}, "2 days, 2 hours, and 30 minutes", ["CCTV Operator","City Administrator","City Mayor"]),
"Request for Research/Photo or Video Documentation/Tour": common("Museum Research, Documentation, and Tour Requests", "Simple / Complex", "G2C - Government to Client", [req("Letter of Request; tour letters must be addressed to the City Mayor","Client")], [step(1,"Submit a research request.","Approve the request and provide the requested research materials.","None","4 days and 10 minutes",["Supervising Tourism Operations Officer","City Information Office"]),step(2,"Submit a request and attend the scheduled photo/video documentation at Museo ng Pamanang Meycaueño.","Approve, schedule, facilitate, and monitor the documentation.","None","2 days and 10 minutes",["Supervising Tourism Operations Officer","City Information Office"]),step(3,"Check tour availability, submit the request, and attend the confirmed tour.","Obtain approval, confirm the schedule, coordinate stakeholders when needed, and facilitate the tour.","None","3 days and 15 minutes for simple; 5 days and 15 minutes for complex",["Supervising Tourism Operations Officer","City Information Office"])], {"amount":"None","description":"No fee"}, "Research: 4 days and 10 minutes; documentation: 2 days and 10 minutes; tour: 3 days and 15 minutes simple or 5 days and 15 minutes complex", ["Supervising Tourism Operations Officer","Office of the City Information Officer - Tourism and Cultural Affairs Division"]),
"Free Legal Consultation": common("Free Legal Consultation", "Highly Technical", "G2C - Government to Client", [req("All documents relevant to the legal concern","Client, requesting office, or employee")], [step(1,"Present the documents related to the concern.","Record and refer the request, assess the issue, and provide legal advice.","None","13 minutes",["City Legal Officer","Office of the City Legal Officer"]),step(2,"Complete the Client Rater Form.","Provide the Client Rater Form.","None","2 minutes",["City Legal Officer","Office of the City Legal Officer"])], {"amount":"None","description":"No fee"}, "15 minutes", ["City Legal Officer","Office of the City Legal Officer"]),
}

eligibility = {
    "Truck Ban and Total Truck Ban Exemption Certificate Issuance": "Truck owners, operators, businesses, and establishments requesting an exemption",
    "Request for Research/Photo or Video Documentation/Tour": "Researchers, students, visitors, organizations, and members of the general public",
    "Free Legal Consultation": "City government offices, officials, employees, and clients seeking legal guidance",
}

data=json.loads(PATH.read_text(encoding="utf-8")); found=set()
for item in data["services"]:
    name=item.get("service_name")
    if name in updates:
        item.update(updates[name])
        if name in eligibility:
            item["who_may_avail"] = eligibility[name]
        found.add(name)
missing=set(updates)-found
if missing: raise SystemExit(f"Services not found: {sorted(missing)}")
PATH.write_text(json.dumps(data,indent=2,ensure_ascii=False),encoding="utf-8")
print(f"Transcribed {len(found)} final Charter services")
