import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/"src/data/citizens-charter/citizens-charter.json"
staff=["Revenue Collection Clerk I","Administrative Aide I","Administrative Assistant V","Senior Administrative Assistant I","Local Revenue Collection Officer II","Office of the City Treasurer"]
def r(name,source="Applicant"): return {"requirement":name,"where_to_secure":source}
def representative(): return [r("Authorization Letter or Special Power of Attorney / Board Resolution / Secretary's Certificate, when represented","Person or company represented"),r("Government-issued IDs of the owner and representative, each with three specimen signatures (original and 1 photocopy)","Government issuing agency")]

updates={
"Community Tax Certificate (CTC/Cedula) Payment and Issuance":{
 "plain_language_name":"Community Tax Certificate (Cedula)","requirements":[r("Accomplished CTC form","City Treasurer"),r("Previous CTC, if available (original or 1 photocopy)"),r("Required personal or business information, including prior-year income/gross receipts or assessed property value")]+representative(),
 "client_steps":[{"step":1,"action":"Get a queue number, complete the form, and submit the information and documents for verification and assessment.","processing_time":"12 minutes"},{"step":2,"action":"Pay the assessed community tax and receive the issued CTC.","processing_time":"8 minutes"}],"fees":{"amount":"Varies","description":"Computed under the Local Government Code from income, gross receipts, or assessed property value."},"processing_time":"20 minutes","person_responsible":staff},
"Professional Tax Receipt (PTR) Payment":{
 "requirements":[r("Valid PRC ID or professional license"),r("Previous PTR or Official Receipt for renewal")]+representative(),"client_steps":[{"step":1,"action":"Present the professional license for checking, encoding, and PTR preparation.","processing_time":"9 minutes"},{"step":2,"action":"Pay the professional tax and receive the PTR.","processing_time":"6 minutes"}],"fees":{"amount":"₱300","description":"₱300 if paid by January 31; statutory penalties apply afterward."},"processing_time":"15 minutes","person_responsible":staff},
"Miscellaneous Fees and Charges Payment":{
 "requirements":[r("Order of Payment","Concerned city office")]+representative(),"client_steps":[{"step":1,"action":"Get a queue number and submit the Order of Payment for verification and system encoding.","processing_time":"8 minutes"},{"step":2,"action":"Pay the assessed amount and receive the Official Receipt.","processing_time":"7 minutes"}],"fees":{"amount":"Varies","description":"Based on the amount assessed by the concerned city office."},"processing_time":"15 minutes","person_responsible":staff},
"Real Property Transfer Tax Payment":{
 "requirements":[r("Original or Certified True Copy of Title (original and 1 photocopy)","Registry of Deeds or owner"),r("Real Property Tax Receipt (original and 1 photocopy)","Owner or City Treasurer"),r("Tax Clearance (original and 1 photocopy)","City Treasurer"),r("Tax Declaration (original and 1 photocopy)","City Assessor"),r("Notarized Deed of Conveyance, such as sale, donation, or extrajudicial settlement","Owner or Notary Public")]+representative(),
 "client_steps":[{"step":1,"action":"Submit the documents for verification, transfer-tax computation, and issuance of the Order of Payment.","processing_time":"48 minutes for simple computation or 2 hours for complex computation"},{"step":2,"action":"Pay the transfer tax and receive the Official Receipt.","processing_time":"5 minutes"}],"fees":{"amount":"Varies","description":"75% of 1% of the total consideration or fair market value, whichever is higher."},"processing_time":"53 minutes for simple computation or 2 hours and 5 minutes for complex computation","person_responsible":staff},
"Traffic Violation Payment":{
 "requirements":[r("Duplicate copy of Traffic Violation Receipt","Meycauayan traffic enforcer or Traffic Management Division")]+representative(),"client_steps":[{"step":1,"action":"Present the Traffic Violation Receipt for review, verification, and assessment.","processing_time":"8 minutes"},{"step":2,"action":"Pay the applicable penalty and receive the Official Receipt.","processing_time":"7 minutes"}],"fees":{"amount":"Varies","description":"Refer to the Police Citation Violations schedule of fees."},"processing_time":"15 minutes","person_responsible":staff},
"Certified True Copy of Receipts Issuance":{
 "plain_language_name":"Certified True Copy of an Official Receipt","requirements":[r("Original receipt to be certified, if available")]+representative(),"client_steps":[{"step":1,"action":"Submit the receipt and authorization documents for verification and issuance of an Order of Payment.","processing_time":"9 minutes"},{"step":2,"action":"Pay the certification fee and receive the certified copy.","processing_time":"18 minutes"}],"fees":{"amount":"₱50","description":"Certified-copy fee"},"processing_time":"27 minutes","person_responsible":staff},
"Tax Clearance Issuance":{
 "requirements":[r("Real Property Tax Receipt (original or 1 photocopy)","Owner or City Treasurer"),r("Certified True Copy of Tax Declaration (original signed copy)","City Assessor"),r("Community Tax Certificate (original or 1 photocopy)","City Treasurer")]+representative(),"client_steps":[{"step":1,"action":"Submit the documents for verification of updated real-property tax payments.","processing_time":"10 minutes"},{"step":2,"action":"Pay the clearance fee and wait for preparation and approval.","processing_time":"31 minutes"},{"step":3,"action":"Receive the Tax Clearance.","processing_time":"2 minutes"}],"fees":{"amount":"₱50","description":"₱50 per clearance"},"processing_time":"43 minutes","person_responsible":staff},
"Business Tax and Regulatory Fees Assessment and Payment":{
 "plain_language_name":"Business Tax Assessment and Payment","requirements":[r("Accomplished Business Permit Application Form","CBPLO"),r("Zoning Clearance","City Planning and Development Office"),r("Building Permit, Occupancy Permit, or Change of Use certification","City Engineer"),r("Barangay Business Clearance","Barangay Hall"),r("Community Tax Certificate","City Treasurer"),r("Capital-investment or paid-up-capital documents"),r("Business registration documents from DTI, SEC, or CDA","DTI, SEC, or CDA"),r("Tax-exemption certificate and other sector-specific permits, when applicable","Relevant government agency")]+representative(),"client_steps":[{"step":1,"action":"Submit the business application and requirements for verification and tax assessment.","processing_time":"30 minutes"},{"step":2,"action":"Pay the assessed business tax and regulatory fees and receive the Official Receipt.","processing_time":"15 minutes"}],"fees":{"amount":"Varies","description":"Refer to the City Revenue Code and the issued business-tax assessment."},"processing_time":"45 minutes; some applications may require up to 3 days for validation","person_responsible":staff},
"Business Certification Issuance":{
 "plain_language_name":"City Treasurer Business Certification","requirements":[r("Written request stating the certification needed"),r("Business Permit or Official Receipt, when available")]+representative(),"client_steps":[{"step":1,"action":"Submit the request and supporting business records for verification.","processing_time":"15 minutes"},{"step":2,"action":"Pay the assessed certification fee and receive the certification.","processing_time":"15 minutes"}],"fees":{"amount":"Varies","description":"Based on the applicable certification fee under the City Revenue Code."},"processing_time":"30 minutes","person_responsible":staff},
}

data=json.loads(PATH.read_text(encoding="utf-8")); found=set()
for service in data["services"]:
    name=service.get("service_name")
    if name in updates:
        service.update(updates[name]); found.add(name)
missing=set(updates)-found
if missing: raise SystemExit(f"Services not found: {sorted(missing)}")
PATH.write_text(json.dumps(data,indent=2,ensure_ascii=False),encoding="utf-8")
print(f"Transcribed {len(found)} City Treasurer services")
