import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/"src/data/citizens-charter/citizens-charter.json"
staff=["Administrative Aide II","Administrative Officer I","Registration Officer III","Assistant Registration Officer","Acting City Civil Registrar","Office of the City Civil Registrar"]
def r(name,source): return {"requirement":name,"where_to_secure":source}
def steps(processing,posting=None):
    out=[{"step":1,"action":"Submit the complete documents for review, verification, and assessment.","processing_time":"10 minutes"},{"step":2,"action":"Pay the assessed fee at the City Treasurer and present the Official Receipt.","processing_time":"10 minutes"}]
    if posting: out.append({"step":3,"action":f"Wait for the required {posting} and agency review.","processing_time":posting})
    out.append({"step":len(out)+1,"action":"Receive the registered, corrected, or endorsed civil-registry document.","processing_time":processing})
    return out

common_id=[r("Valid government-issued ID of the applicant","Government issuing agency")]
updates={
"Registration of Live Birth of Person/s with No Known Parents":{
 "plain_language_name":"Register a Foundling or Person with No Known Parents","classification":"Complex","type_of_transaction":"G2C/G2G – Government to Citizen / Government to Government","who_may_avail":"The finder, social welfare agency, or authorized custodian",
 "requirements":[r("Foundling Certificate and duly accomplished civil-registry forms","City Social Welfare Office and City Civil Registrar"),r("Police report or barangay certification on the circumstances of finding","PNP or Barangay Hall"),r("Social case study and custody documents","City Social Welfare Office")]+common_id,"client_steps":steps("15 minutes","required posting and agency validation"),"fees":{"amount":"Varies","description":"Based on the registration and certification requested."},"processing_time":"Subject to posting and agency validation","person_responsible":staff},
"Registration of Legitimation/Acknowledgement of Paternity":{
 "plain_language_name":"Legitimation or Acknowledgement of Paternity","requirements":[r("PSA or Local Civil Registry copy of the child's Birth Certificate","PSA or City Civil Registrar"),r("Marriage Certificate of the parents, when legitimation applies","PSA or City Civil Registrar"),r("Affidavit of Legitimation or Affidavit of Acknowledgement/Admission of Paternity","City Civil Registrar or Notary Public"),r("Affidavit to Use the Surname of the Father, when applicable","City Civil Registrar or Notary Public")]+common_id,"client_steps":steps("15 minutes"),"fees":{"amount":"₱550","description":"Registration, annotation, and endorsement fees"},"processing_time":"35 minutes","person_responsible":staff},
"Out-of-Town Registration of Birth Certificate for Submission to Another City or Municipality":{
 "plain_language_name":"Submit an Out-of-Town Birth Registration","requirements":[r("Accomplished Certificate of Live Birth and supporting birth documents","Hospital, health center, or applicant"),r("Certificate of No Record, when required","PSA or receiving Civil Registrar"),r("Affidavit of Out-of-Town Registration","City Civil Registrar or Notary Public")]+common_id,"client_steps":steps("5 minutes"),"fees":{"amount":"None","description":"No city fee shown"},"processing_time":"20 minutes, excluding delivery to the receiving civil registrar","person_responsible":staff},
"Out-of-Town Registration of Birth Certificate Received for Registration in Meycauayan":{
 "plain_language_name":"Process an Out-of-Town Birth Record Received by Meycauayan","requirements":[r("Endorsed out-of-town registration packet","Originating City or Municipal Civil Registrar"),r("Certificate of Live Birth and complete supporting documents","Originating Civil Registrar")],"client_steps":steps("8 minutes"),"fees":{"amount":"None","description":"No city fee shown"},"processing_time":"23 minutes","person_responsible":staff},
"Marriage License Issuance":{
 "plain_language_name":"Marriage License","requirements":[r("Birth or baptismal certificates of both applicants","PSA, Civil Registrar, or church"),r("Community Tax Certificates and valid IDs of both applicants","City Treasurer and government issuing agency"),r("Parental consent or advice when required by age","Parents or guardians"),r("Pre-Marriage Counseling or Family Planning Certificate","City Population or Health Office"),r("Certificate of No Marriage Record, when required","PSA"),r("Foreign-national documents, when applicable","Embassy, consulate, or immigration authority")],"client_steps":steps("4 minutes","10-day public posting"),"fees":{"amount":"₱300","description":"Marriage-license fee"},"processing_time":"44 minutes plus 10 days posting","person_responsible":staff},
"Issuance of Marriage Affidavit (Article 34)":{
 "plain_language_name":"Marriage Affidavit under Article 34","requirements":[r("Valid IDs and Community Tax Certificates of both parties","Government issuing agency and City Treasurer"),r("Proof that the couple has lived together as spouses for at least five years","Applicant and supporting witnesses"),r("Article 34 joint affidavit","City Civil Registrar or Notary Public")],"client_steps":steps("10 minutes"),"fees":{"amount":"₱200","description":"Affidavit fee"},"processing_time":"30 minutes","person_responsible":staff},
"Correction of Clerical Error (Certificate of Live Birth)":{
 "plain_language_name":"Correct a Clerical Error in a Birth Certificate","requirements":[r("PSA and Local Civil Registry copies of the Birth Certificate","PSA and City Civil Registrar"),r("At least two public or private documents supporting the correct entry","School, employer, church, or government agency"),r("NBI or police clearance and publication documents, when required","NBI, PNP, and newspaper")]+common_id,"client_steps":steps("Finality and PSA endorsement","10-day posting and statutory review"),"fees":{"amount":"₱1,000","description":"Petition fee; publication and documentary costs are separate."},"processing_time":"Subject to 10-day posting, statutory review, and PSA endorsement","person_responsible":staff},
"Correction of Clerical Error (Certificate of Marriage)":{
 "plain_language_name":"Correct a Clerical Error in a Marriage Certificate","requirements":[r("PSA and Local Civil Registry copies of the Marriage Certificate","PSA and City Civil Registrar"),r("Supporting civil-registry and identity documents proving the correct entry","PSA and government issuing agencies"),r("NBI or police clearance and publication documents, when required","NBI, PNP, and newspaper")]+common_id,"client_steps":steps("Finality and PSA endorsement","10-day posting and statutory review"),"fees":{"amount":"₱1,000","description":"Petition fee; publication and documentary costs are separate."},"processing_time":"Subject to 10-day posting, statutory review, and PSA endorsement","person_responsible":staff},
"Correction of Clerical Error (Certificate of Death)":{
 "plain_language_name":"Correct a Clerical Error in a Death Certificate","requirements":[r("PSA and Local Civil Registry copies of the Death Certificate","PSA and City Civil Registrar"),r("Supporting records proving the correct entry","Hospital, church, PSA, or government agency"),r("Proof of relationship and applicant's valid ID","PSA and government issuing agency")],"client_steps":steps("Finality and PSA endorsement","10-day posting and statutory review"),"fees":{"amount":"₱1,000","description":"Petition fee; publication and documentary costs are separate."},"processing_time":"Subject to 10-day posting, statutory review, and PSA endorsement","person_responsible":staff},
"Correction of First Name, Birth Date, or Gender under R.A. 9048 and R.A. 10172":{
 "plain_language_name":"Correct First Name, Birth Date, or Sex in a Civil Record","requirements":[r("PSA and Local Civil Registry copies of the affected record","PSA and City Civil Registrar"),r("Earliest school, medical, baptismal, employment, and identity records supporting the correction","Relevant institution"),r("NBI and police clearances","NBI and PNP"),r("Newspaper publication and affidavit of publication","Newspaper publisher"),r("Medical certification for correction of sex or birth date, when required","Accredited physician or hospital")]+common_id,"client_steps":steps("Finality and PSA endorsement","10-day posting, publication, and statutory review"),"fees":{"amount":"Varies","description":"Petition fee under R.A. 9048/R.A. 10172; publication and documentary costs are separate."},"processing_time":"Subject to publication, statutory review, and PSA endorsement","person_responsible":staff},
"Migrant Petition for Correction":{
 "plain_language_name":"File a Migrant Petition for Civil-Record Correction","requirements":[r("Certified civil-registry record to be corrected","PSA and civil registrar where the record is registered"),r("Complete petition and supporting evidence required for the requested correction","Applicant and originating civil registrar"),r("Proof of Meycauayan residence and valid ID","Barangay Hall and government issuing agency")],"client_steps":steps("5 minutes","posting and transmittal to the civil registrar of origin"),"fees":{"amount":"Varies","description":"Applicable correction fee plus mailing, publication, and documentary expenses."},"processing_time":"Subject to the originating civil registrar's action","person_responsible":staff},
"Supplemental Report":{
 "plain_language_name":"Add a Missing Entry through a Supplemental Report","requirements":[r("PSA and Local Civil Registry copies of the affected certificate","PSA and City Civil Registrar"),r("Affidavit for Supplemental Report","City Civil Registrar or Notary Public"),r("Documents supporting the omitted entry","Relevant school, hospital, church, or government office")]+common_id,"client_steps":steps("12 minutes"),"fees":{"amount":"₱50","description":"Supplemental-report endorsement fee"},"processing_time":"32 minutes, excluding PSA processing","person_responsible":staff},
"Endorsement of Civil Registry Documents":{
 "plain_language_name":"Endorse Civil Registry Documents to PSA","requirements":[r("Registered civil-registry document for advance endorsement or inclusion","City Civil Registrar"),r("Official Receipt and valid ID","City Treasurer and government issuing agency")],"client_steps":steps("2 minutes"),"fees":{"amount":"₱50","description":"Endorsement fee"},"processing_time":"10 minutes for advance endorsement or 22 minutes for inclusion/verification","person_responsible":staff},
"Registration of Court Decision":{
 "plain_language_name":"Register a Court Decision Affecting a Civil Record","requirements":[r("Certified court decision and Certificate of Finality","Issuing court"),r("Certificate of Registration or annotation documents required by PSA","Court or City Civil Registrar"),r("PSA and Local Civil Registry copies of the affected record","PSA and City Civil Registrar")]+common_id,"client_steps":steps("15 minutes"),"fees":{"amount":"₱600-₱1,100","description":"₱600 for court-decision registration or ₱1,100 when an applicable annotation/recognition procedure is required."},"processing_time":"Subject to court-document validation and PSA endorsement","person_responsible":staff},
}

data=json.loads(PATH.read_text(encoding="utf-8")); found=set()
for service in data["services"]:
    name=service.get("service_name")
    if name in updates:
        service.update(updates[name]); found.add(name)
missing=set(updates)-found
if missing: raise SystemExit(f"Services not found: {sorted(missing)}")
PATH.write_text(json.dumps(data,indent=2,ensure_ascii=False),encoding="utf-8")
print(f"Transcribed {len(found)} Civil Registrar services")
