import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/"src/data/citizens-charter/citizens-charter.json"
def r(name,source): return {"requirement":name,"where_to_secure":source}
def record(reqs,actions,fee,time,people,name=None):
    d={"requirements":reqs,"client_steps":[{"step":i+1,"action":a,"processing_time":"See total processing time"} for i,a in enumerate(actions)],"fees":{"amount":fee,"description":"No fee" if fee=="None" else "Refer to the applicable hospital or city fee schedule."},"processing_time":time,"person_responsible":people}
    if name:d["plain_language_name"]=name
    return d
cho=["City Health Officer","City Health Office personnel","Office of the City Treasurer"]
cmdc=["Attending physician","Nurse","Medical Records or Billing personnel","City of Meycauayan Diagnostic Center"]
updates={
"Issuance of Health Certificate / Id":record([r("Laboratory results and health-card application","Accredited laboratory and City Health Office"),r("Official Receipt","City Treasurer")],["Submit the requirements for review and assessment.","Pay the fee and undergo health evaluation.","Receive the Health Certificate or ID."],"₱150","22 minutes",cho,"Health Certificate and ID"),
"Burial, Cremation, Exhumation, and Transfer Permit Issuance":record([r("Death Certificate","City Civil Registrar"),r("Request and supporting cemetery or funeral documents","Funeral service, cemetery, or applicant"),r("Official Receipt","City Treasurer")],["Submit the documents for validation.","Pay the applicable fee.","Receive the burial, cremation, exhumation, or transfer permit."],"₱50","22 minutes",cho),
"Pre-Marriage Counseling Certificate for Family Planning":record([r("Marriage License application or referral","City Civil Registrar"),r("Valid IDs of the couple","Government issuing agency")],["Register for the counseling session.","Attend pre-marriage and family-planning counseling.","Receive the certificate."],"None","53 minutes",["Population Program Officer","City Health Office counselor"],"Pre-Marriage Counseling Certificate"),
"Issuance of Medical Social Worker Recommendation":record([r("Clinical abstract and physician referral","Hospital physician"),r("Proof of identity and financial or residency documents","Applicant and Barangay Hall")],["Submit documents and undergo social-work intake and assessment.","Wait for verification and preparation of the recommendation.","Receive the Medical Social Worker recommendation and requirements list."],"None","2 days and 56 minutes",["Medical Social Worker","CMDC"]),
"Managing Inter-Agency Referral":record([r("Referral letter and medical or social case documents","Referring agency")],["Submit the referral for intake and inter-agency coordination.","Wait for case validation and endorsement.","Receive the completed referral or Social Case Study documentation."],"None","3 days and 5 minutes",["Medical Social Worker","CMDC"]),
"Receiving Schedule of Hemodialysis Treatment":record([r("Nephrologist's order or dialysis referral","Attending nephrologist"),r("Dialysis laboratory and medical requirements","Hospital or laboratory")],["Submit the dialysis referral and records.","Coordinate an available treatment slot.","Receive the treatment schedule."],"None","25 minutes",["Dialysis Nurse","CMDC"]),
"Registration on Philhealth Dialysis Database":record([r("PhilHealth membership and eligibility documents","PhilHealth"),r("Patient Dialysis Database Form and treatment records","CMDC")],["Submit and verify patient and PhilHealth information.","Register the patient in the dialysis database.","Receive the acknowledged database form."],"None","14 minutes",["PhilHealth Officer","CMDC"]),
"Procedure for Hemodialysis Treatment":record([r("Confirmed dialysis schedule","CMDC Dialysis Unit"),r("Physician's orders and required laboratory results","Attending physician or laboratory")],["Register and undergo pre-dialysis assessment.","Receive the prescribed hemodialysis treatment.","Complete post-treatment monitoring and documentation."],"None","5 hours",["Dialysis Nurse","Nephrologist","CMDC"]),
"Discharge of Hemodialysis Patient":record([r("Completed dialysis treatment record and physician clearance","CMDC Dialysis Unit")],["Complete post-dialysis assessment.","Settle or validate billing and benefit documents.","Receive discharge clearance."],"None","12 minutes",["Dialysis Nurse","Billing Officer","CMDC"]),
"Releasing of Medical Records":record([r("Medical-record request and valid ID","Applicant"),r("Authorization and IDs when requested by a representative","Patient and representative")],["Submit the request and authorization for validation.","Wait for retrieval, preparation, and approval.","Receive and acknowledge the released medical record."],"None","2 days and 7 minutes",["Medical Records Officer","CMDC"]),
"Laboratory Services":record([r("Laboratory request from an authorized clinician","Doctor or City Health Unit"),r("Patient identification and specimen as instructed","Applicant")],["Register and submit the laboratory request.","Undergo specimen collection and testing.","Receive the validated laboratory result personally or through the referring CHU."],"Varies","30 minutes",["Registered Medical Technologist","Diagnostic Center"]),
"General Radiography":record([r("Radiology request","Attending physician"),r("Patient identification and prior imaging when relevant","Applicant")],["Register and submit the imaging request.","Prepare for and undergo the X-ray examination.","Receive the interpreted result."],"Varies","40 minutes",["Radiologic Technologist","Radiology Clerk","Radiologist"]),
"Ultrasonography":record([r("Ultrasound request","Attending physician"),r("Patient identification and required preparation","Applicant")],["Register and submit the request.","Undergo the ultrasound examination.","Receive the interpreted result."],"Varies","50 minutes",["Sonologist","Radiology Clerk","Radiologist"]),
"Outpatient Department":record([r("Patient information and available previous medical records","Applicant")],["Register and undergo triage and vital-sign assessment.","Receive medical consultation and diagnostic orders when needed.","Receive treatment advice, prescription, referral, or medicine."],"None","49 minutes",cmdc),
"Emergency Department":record([r("No documentary requirement for emergency stabilization","None")],["Proceed immediately to emergency triage.","Undergo physician assessment and emergency treatment.","Receive discharge, referral, transfer, or admission instructions."],"Varies","40 minutes",["Emergency physician","Emergency nurse","CMDC"]),
"Inpatient Department":record([r("Admission order and patient information","Attending physician and applicant")],["Complete ward admission and nursing assessment.","Receive inpatient medical and nursing care.","Complete discharge orders and billing clearance."],"Varies","1 hour and 35 minutes for discharge processing",cmdc),
"Admitting Section":record([r("Physician's admission order","Attending physician"),r("Patient identification and PhilHealth or benefit documents, if available","Applicant and PhilHealth")],["Submit the admission order and patient details.","Complete registration, room assignment, and consent forms.","Proceed to the assigned ward; financial assistance referral is provided when needed."],"Varies","45 minutes",["Admitting Staff","Patient or companion","CMDC"]),
"Out-Patient Department Transaction":record([r("Valid prescription or medicine request from the Outpatient Department","CMDC physician")],["Submit the prescription for validation.","Receive and acknowledge available medicines.","Pharmacy staff records the transaction."],"None","11 minutes",["Pharmacy Personnel","CMDC"]),
"Emergency Department Transaction":record([r("Valid prescription or medicine request from the Emergency Department","CMDC physician")],["Submit the prescription for validation.","Receive and acknowledge available emergency medicines.","Pharmacy staff records the transaction."],"None","9 minutes",["Pharmacy Personnel","CMDC"]),
"Return of Medicines to Pharmacy Department":record([r("Unused medicine issued by the CMDC Pharmacy and related patient record","Patient or ward")],["Return eligible unused medicine for inspection.","Pharmacy staff validates and records the return."],"None","5 minutes",["Pharmacy Personnel","CMDC"]),
}
data=json.loads(PATH.read_text(encoding="utf-8")); found=set()
for s in data["services"]:
    n=s.get("service_name")
    if n in updates:s.update(updates[n]);found.add(n)
missing=set(updates)-found
if missing:raise SystemExit(f"Services not found: {sorted(missing)}")
PATH.write_text(json.dumps(data,indent=2,ensure_ascii=False),encoding="utf-8")
print(f"Transcribed {len(found)} health and medical services")
