import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; PATH=ROOT/"src/data/citizens-charter/citizens-charter.json"
staff=["Social Welfare Assistant","Social Welfare Officer III","Office of the City Social Welfare and Development Officer"]
def r(name,source):return {"requirement":name,"where_to_secure":source}
def entry(name,reqs,actions,time,people=None):return {"plain_language_name":name,"requirements":reqs,"client_steps":[{"step":i+1,"action":a,"processing_time":"See total processing time"} for i,a in enumerate(actions)],"fees":{"amount":"None","description":"No fee"},"processing_time":time,"person_responsible":people or staff}
updates={
"CSWDO Certificate of Indigency / Financial Incapability Issuance":entry("Certificate of Indigency or Financial Incapability",[r("Barangay Certificate of Indigency or residency","Barangay Hall"),r("Valid ID of applicant or representative","Government issuing agency"),r("Supporting purpose-specific document, such as a medical abstract, billing statement, school request, or legal referral","Requesting institution")],["Submit the documents and undergo intake interview.","Wait for verification and preparation of the certificate.","Sign the release logbook and receive the certificate."],"40 minutes"),
"Parental Capability Assessment Report (PCAR) Issuance":entry("Parental Capability Assessment Report",[r("Court, DSWD, RACCO, or child-caring agency referral","Referring court or agency"),r("Birth certificates and valid IDs of parents and children","PSA and government issuing agencies"),r("Marriage certificate or proof of civil status","PSA or City Civil Registrar"),r("Barangay clearance and proof of residence","Barangay Hall"),r("Income, employment, medical, and other documents requested during assessment","Applicant and relevant agencies")],["Submit the referral and documents for case intake.","Participate in interviews, home visits, collateral interviews, and case conferences.","Wait for report preparation, review, and approval.","Receive the PCAR personally or through the requesting agency or email."],"20 working days and 25 minutes"),
"Home Study and/or Child Study Report for Adoption of Child Issuance":entry("Home or Child Study Report for Adoption",[r("Application and referral from the Regional Alternative Child Care Office or authorized agency","RACCO or authorized child-caring agency"),r("Birth, marriage, and civil-status documents of the child and prospective adoptive parents","PSA and City Civil Registrar"),r("Medical, NBI, police, income, and character-reference documents","Hospital, NBI, PNP, employer, and references"),r("Certificate of attendance at an Adoption Forum","RACCO or authorized agency"),r("Written consent to adoption and required photographs","Prospective adoptive parents")],["Submit the adoption referral and complete documents.","Undergo interviews, home assessment, collateral investigation, and case conferences.","Wait for preparation, review, and approval of the Home or Child Study Report.","Receive notice that the report was forwarded to RACCO."],"64 working days and 30 minutes"),
"Social Case Study Report with Discernment Issuance":entry("Social Case Study and Discernment Assessment",[r("Court, prosecutor, police, barangay, or social welfare referral","Referring agency"),r("Birth certificate or proof of age of the child","PSA or City Civil Registrar"),r("Valid IDs and proof of relationship of the parent or guardian","Government issuing agency and PSA"),r("Police, complaint, or case documents","PNP, prosecutor, or court")],["Submit the referral and documents for intake.","The child and guardian participate in interviews and discernment assessment.","The social worker prepares and reviews the Social Case Study Report.","The report is released to or filed for the requesting authority."],"3 hours and 5 minutes"),
"Early Childhood Care and Development (Day Care) Application":entry("Day Care Enrollment",[r("Child's Birth Certificate (photocopy)","PSA or City Civil Registrar"),r("Parent or guardian's valid ID","Government issuing agency"),r("Child health or immunization record","Health center or pediatrician"),r("Barangay residency certification, when requested","Barangay Hall")],["Visit the assigned Child Development Center and submit the child's records.","Complete the enrollment form and parent interview.","Wait for verification and class assignment.","Receive enrollment confirmation and sign the release logbook."],"1 day and 55 minutes",["Day Care Worker I","Office of the City Social Welfare and Development Officer"]),
"Certificate of Guardianship Issuance":entry("Certificate of Guardianship",[r("Birth Certificate of the child","PSA or City Civil Registrar"),r("Valid IDs of guardian and child, when available","Government issuing agency"),r("Court order, notarized guardianship document, or referral supporting the request","Court, Notary Public, or requesting agency"),r("Barangay certification of residence and relationship","Barangay Hall")],["Submit the guardianship documents and undergo intake interview.","Wait for verification and preparation of the certificate.","Receive the Certificate of Guardianship."],"40 minutes"),
}
data=json.loads(PATH.read_text(encoding="utf-8"));found=set()
for s in data["services"]:
 n=s.get("service_name")
 if n in updates:s.update(updates[n]);found.add(n)
missing=set(updates)-found
if missing:raise SystemExit(f"Services not found: {sorted(missing)}")
PATH.write_text(json.dumps(data,indent=2,ensure_ascii=False),encoding="utf-8")
print(f"Transcribed {len(found)} social welfare services")
